# Generated by Django 3.2 on 2023-05-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230524_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.TextField(
                choices=[('male', 'male'), ('female', 'female')],
                null=True,
                verbose_name='gender',
            ),
        ),
    ]
