# Generated by Django 4.2.1 on 2023-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_filmwork_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='person',
            field=models.ManyToManyField(through='movies.PersonFilmwork', to='movies.person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='certificate',
            field=models.CharField(max_length=512, null=True, verbose_name='certificate'),
        ),
        migrations.AlterUniqueTogether(
            name='genrefilmwork',
            unique_together={('film_work', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='personfilmwork',
            unique_together={('film_work', 'person', 'role')},
        ),
    ]
