version: '3'
services:
  service:
    container_name: django_movies_app
    build: ./app
    env_file:
      - ./.env
    volumes:
      - ./app/:/opt/app
      - static_value:/opt/app/static/
      - media_value:/opt/app/media/
    expose:
      - "8000"
    depends_on:
      - db

  db:
    container_name: db_movies
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
      - ./dump_db/db_backup-1.sql:/docker-entrypoint-initdb.d/db_backup-1.sql
    env_file:
      - ./.env

  elastic:
    container_name: elastic_movies
    image: elasticsearch:8.6.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ports:
      - "9200:9200"
    depends_on:
      - etl

  etl:
    container_name: etl_movies
    build: ./postgres_to_es
    env_file:
      - ./.env
    volumes:
      - ./postgres_to_es/:/opt/app
    depends_on:
      - db


  nginx:
    container_name: nginx_movies
    image: nginx:1.25.0
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_value:/opt/app/static/
      - media_value:/opt/app/media/
    depends_on:
      - service
    ports:
      - "80:80"

volumes:
  static_value:
  media_value:
