# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"\"\n\x11\x43heckTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x1e\n\x08\x41uthInfo\x12\x12\n\nis_success\x18\x01 \x01(\x08\"4\n\x12\x43heckTokenResponse\x12\x1e\n\x0bvalidations\x18\x01 \x03(\x0b\x32\t.AuthInfo\"7\n\x14\x41uthorizationRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"z\n\x15\x41uthorizationResponse\x12\x32\n\x06tokens\x18\x01 \x03(\x0b\x32\".AuthorizationResponse.TokensEntry\x1a-\n\x0bTokensEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32{\n\x04\x41uth\x12\x37\n\x0c\x43heckerToken\x12\x12.CheckTokenRequest\x1a\x13.CheckTokenResponse\x12:\n\tLoginAuth\x12\x15.AuthorizationRequest\x1a\x16.AuthorizationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHORIZATIONRESPONSE_TOKENSENTRY._options = None
  _AUTHORIZATIONRESPONSE_TOKENSENTRY._serialized_options = b'8\001'
  _globals['_CHECKTOKENREQUEST']._serialized_start=14
  _globals['_CHECKTOKENREQUEST']._serialized_end=48
  _globals['_AUTHINFO']._serialized_start=50
  _globals['_AUTHINFO']._serialized_end=80
  _globals['_CHECKTOKENRESPONSE']._serialized_start=82
  _globals['_CHECKTOKENRESPONSE']._serialized_end=134
  _globals['_AUTHORIZATIONREQUEST']._serialized_start=136
  _globals['_AUTHORIZATIONREQUEST']._serialized_end=191
  _globals['_AUTHORIZATIONRESPONSE']._serialized_start=193
  _globals['_AUTHORIZATIONRESPONSE']._serialized_end=315
  _globals['_AUTHORIZATIONRESPONSE_TOKENSENTRY']._serialized_start=270
  _globals['_AUTHORIZATIONRESPONSE_TOKENSENTRY']._serialized_end=315
  _globals['_AUTH']._serialized_start=317
  _globals['_AUTH']._serialized_end=440
# @@protoc_insertion_point(module_scope)
