# Generated by Django 4.2.1 on 2023-05-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230524_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='certificate',
            field=models.CharField(max_length=512, verbose_name='certificate'),
        ),
    ]
