# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_client import auth_pb2 as auth__pb2


class AuthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckerToken = channel.unary_unary(
                '/Auth/CheckerToken',
                request_serializer=auth__pb2.CheckTokenRequest.SerializeToString,
                response_deserializer=auth__pb2.CheckTokenResponse.FromString,
                )
        self.LoginAuth = channel.unary_unary(
                '/Auth/LoginAuth',
                request_serializer=auth__pb2.AuthorizationRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthorizationResponse.FromString,
                )


class AuthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckerToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckerToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckerToken,
                    request_deserializer=auth__pb2.CheckTokenRequest.FromString,
                    response_serializer=auth__pb2.CheckTokenResponse.SerializeToString,
            ),
            'LoginAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginAuth,
                    request_deserializer=auth__pb2.AuthorizationRequest.FromString,
                    response_serializer=auth__pb2.AuthorizationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Auth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Auth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckerToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Auth/CheckerToken',
            auth__pb2.CheckTokenRequest.SerializeToString,
            auth__pb2.CheckTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoginAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Auth/LoginAuth',
            auth__pb2.AuthorizationRequest.SerializeToString,
            auth__pb2.AuthorizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
