"""add cascade delete

Revision ID: 71909ab163c9
Revises: 6490bd45ead0
Create Date: 2023-08-18 22:48:45.932915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71909ab163c9'
down_revision: Union[str, None] = '6490bd45ead0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'history', ['id'])
    op.drop_constraint('history_user_id_fkey', 'history', type_='foreignkey')
    op.create_foreign_key(None, 'history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'users_roles', ['id'])
    op.drop_constraint('users_roles_user_id_fkey', 'users_roles', type_='foreignkey')
    op.drop_constraint('users_roles_role_id_fkey', 'users_roles', type_='foreignkey')
    op.create_foreign_key(None, 'users_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_roles', type_='foreignkey')
    op.drop_constraint(None, 'users_roles', type_='foreignkey')
    op.create_foreign_key('users_roles_role_id_fkey', 'users_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('users_roles_user_id_fkey', 'users_roles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'users_roles', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.create_foreign_key('history_user_id_fkey', 'history', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'history', type_='unique')
    # ### end Alembic commands ###
